### ISSUE TITLE
version 8.0.0 has incorrect typescript config

### ISSUE THREAD

**Issue by jefbarn** [techniq/odata-query#132]
Could not find the type definitions:

```ts
import OdataQuery, { QueryOptions } from "odata-query";
```

TS7016: Could not find a declaration file for module odata-query.

Also I had to do this before:

```ts
const buildQuery = OdataQuery.default;
```
Is that fixed now?

**Comment by techniq** [comment]
Hey @jefbarn, @enure just [reworked](https://github.com/techniq/odata-query/pull/130) the build so `OdataQuery.default` should no longer be required, but [looks](https://www.npmjs.com/package/odata-query?activeTab=code) like there is an issue with building [types](https://github.com/techniq/odata-query/blob/main/package.json#L12).

![Image](https://github.com/user-attachments/assets/a77d688e-c19f-487a-bd8f-4b28f1d9f745)

I'm a bit covered up but if someone can submit a PR I'll review / release.

**Comment by techniq** [comment]
I haven't been able to track down the root cause of this yet as building locally produces the `index.d.ts` file but it's no longer working when built by the [release](https://github.com/techniq/odata-query/blob/main/.github/workflows/release.yml) pipeline.

![Image](https://github.com/user-attachments/assets/a5d600aa-d042-43b3-85e7-6be299640ee2)

**Comment by techniq** [comment]
Thanks @enure.  Merged and released [8.0.2](https://www.npmjs.com/package/odata-query?activeTab=code) but sadly it didn't include `index.d.ts`

![Image](https://github.com/user-attachments/assets/672de0fd-5377-4d68-b830-b024d55cae78)

Interesting, I'm not seeing it recreated locally now either when I test.

![Image](https://github.com/user-attachments/assets/201cea8a-b8e2-43e0-80cb-1c78fee17d8b)

**Comment by techniq** [comment]
@enure awe, might be related to the outdated `typescript` dependency.

![Image](https://github.com/user-attachments/assets/ad885763-2ca5-436b-9b60-934562d06a5d)

If you have any cycles, could you look at updating/resolving the issues (I know you mentioned you ran into some issues when you attempted in the vite PR).

**Comment by techniq** [comment]
@enure That was it, thanks!

@jefbarn fixed in `8.0.3`

![Image](https://github.com/user-attachments/assets/887f83f2-a507-4343-bfdf-6b5a594ea9c7)

**Comment by jefbarn** [comment]
@techniq Thanks the types are working as they did before. Still have the problem with the default export (you're using
```export { W as default }``` instead of ```export default W``` in the js code which aren't the same.) but that's a minor inconvenience.

**Comment by satispunk** [comment]
Hello, has this issue been addressed?

I have also faced 

```
TS2349: This expression is not callable.
Type
typeof import("C:/dev/npm/forsta/node_modules/odata-query/dist/index")
has no call signatures.
```

**Comment by techniq** [comment]
Hello @satispunk.  This issue has not been addressed yet.

**Comment by au5ton** [comment]
@techniq Is there a reason that `buildQuery` can't _also_ be a non-default export, and avoid this problem entirely? I'm getting this issue in one project but not another and I'm banging my head against the wall. 😓

Edit:
It was `allowSyntheticDefaultImports: true` in tsconfig.json for me that fixed it
